version: '3.8'

services:
  backend-service:
    image: gabopiova/tp4-backend:latest
    container_name: backend-service
    ports:
      - "3000:3000"
    networks:
      - tp4-network

  frontend-web:
    image: gabopiova/tp4-frontend:latest
    container_name: frontend-web
    ports:
      - "8080:80"
    networks:
      - tp4-network
    depends_on:
      - backend-service

networks:
  tp4-network:
    driver: bridge